version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
services:
  - mssql2017
nuget:
  disable_publish_on_pr: true
artifacts:
- path: **\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: DihPu6lVgIjYKLBCmijz+hHU5oqrQfyJlSbXM/3KWHRMKcdiavdk/mYRcECBGBdP
  on:
    appveyor_repo_tag: true