// <auto-generated />
using System;
using EFCore.TimeTravelerTests.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore.TimeTravelerTests.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191210154702_WormFriendsAndWeapons")]
    partial class WormFriendsAndWeapons
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCore.TimeTravelerTests.Apple", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FruitStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Apple");
                });

            modelBuilder.Entity("EFCore.TimeTravelerTests.Worm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppleId");

                    b.ToTable("Worm");
                });

            modelBuilder.Entity("EFCore.TimeTravelerTests.WormFriendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("WormAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WormBId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WormAId");

                    b.HasIndex("WormBId");

                    b.ToTable("WormFriendship");
                });

            modelBuilder.Entity("EFCore.TimeTravelerTests.WormWeapon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WormId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WormId");

                    b.ToTable("WormWeapon");
                });

            modelBuilder.Entity("EFCore.TimeTravelerTests.Worm", b =>
                {
                    b.HasOne("EFCore.TimeTravelerTests.Apple", "Apple")
                        .WithMany("Worms")
                        .HasForeignKey("AppleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore.TimeTravelerTests.WormFriendship", b =>
                {
                    b.HasOne("EFCore.TimeTravelerTests.Worm", "WormA")
                        .WithMany("FriendshipsA")
                        .HasForeignKey("WormAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCore.TimeTravelerTests.Worm", "WormB")
                        .WithMany("FriendshipsB")
                        .HasForeignKey("WormBId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFCore.TimeTravelerTests.WormWeapon", b =>
                {
                    b.HasOne("EFCore.TimeTravelerTests.Worm", "Worm")
                        .WithMany("Weapons")
                        .HasForeignKey("WormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
