// <auto-generated />
using System;
using EFCore.TimeTravelerTests.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore.TimeTravelerTests.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191209212051_TemporalApples")]
    partial class TemporalApples
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HistoryOfFruit.Apple", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FruitStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Apples");
                });
#pragma warning restore 612, 618
        }
    }
}
